DECLARE
FK_NAME VARCHAR(30);
BEGIN
  SELECT UC.CONSTRAINT_NAME INTO FK_NAME
  FROM USER_CONSTRAINTS UC INNER JOIN USER_CONS_COLUMNS UCC ON UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME
  WHERE UC.CONSTRAINT_TYPE='R' AND UC.TABLE_NAME='REFERENCETABLE' AND UCC.COLUMN_NAME='DROPTABLEID';

  EXECUTE IMMEDIATE 'ALTER TABLE ReferenceTable DROP CONSTRAINT ' || FK_NAME;
END;
;


-- Drop no longer exisiting table
DROP TABLE DropTable;

-- Dropped columns of table ReferenceTable
ALTER TABLE ReferenceTable DROP COLUMN DropTableId;