package ${packageName};

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;

import ch.ivyteam.ivy.persistence.IPersistentObject;
import ch.ivyteam.ivy.persistence.IPersistentTransaction;
import ch.ivyteam.ivy.persistence.restricted.db.meta.KeyType;
import ch.ivyteam.ivy.persistence.restricted.db.meta.Table;
import ch.ivyteam.ivy.persistence.restricted.db.meta.TableColumn;
import ch.ivyteam.ivy.persistence.restricted.db.meta.TableColumn.Type;
import ch.ivyteam.ivy.persistence.restricted.db.meta.TableColumn.Option;
<#if table.query??>  
import ch.ivyteam.ivy.persistence.restricted.db.meta.ViewColumn;
</#if>
import ch.ivyteam.ivy.persistence.PersistencyException;
import ch.ivyteam.ivy.persistence.db.DatabasePersistencyService;
import ch.ivyteam.ivy.persistence.db.DatabaseTableClassPersistencyService;
import ch.ivyteam.db.sql.ColumnName;
import ${table.entityClass};

/**
 * ----------------------------------------------------------------------<br>
 * This code was generated by the JavaClassPersistencyServiceImplemenationGenerator.<br>
 * Do not edit this class instead edit the meta information this class was generated of.<br>
 * ----------------------------------------------------------------------<br>
 * Class Persistency Service Implementation for table ${table.name}<br>
 * ----------------------------------------------------------------------<br>
 * This class is responsible to provide CRUD operations for the table ${table.name}<br>
 * and a relation to object mapping for the entity class ${table.simpleEntityClass}<br>
 * ----------------------------------------------------------------------<br>
 * ${table.comment}
 * ----------------------------------------------------------------------<br>
 */

public class Db${table.simpleEntityClass} extends DatabaseTableClassPersistencyService<${table.simpleEntityClass}>
{
  /** Name of the DB Table */
  public static final String TABLENAME = "${table.name}";
<#if table.query??>  
  /** The Name of the table to use in the query */
  public static final String QUERY_TABLENAME = "${table.query}";
</#if>
  /** Name of the primary key column */
  private static final String PRIMARY_KEY_COLUMN_NAME = "${table.primaryKey.name}";
  /** Full qualified name of the parent key column  */
  public static final ColumnName PRIMARY_KEY_COLUMN = new ColumnName(TABLENAME, PRIMARY_KEY_COLUMN_NAME);
<#if table.parentKey??>  
  /** Name of the parent Key column */
  private static final String PARENT_FOREIGN_KEY_COLUMN_NAME = "${table.parentKey.name}";
  /** Full qualified name of the parent key column  */
  public static final ColumnName PARENT_FOREIGN_KEY_COLUMN = new ColumnName(TABLENAME, PARENT_FOREIGN_KEY_COLUMN_NAME);
</#if>
<#if table.fieldForOptimisticLocking??>  
  /** Name of the optimistic locking column */
  private static final String OPTIMISTIC_LOCKING_COLUMN_NAME = "${table.fieldForOptimisticLocking.name}";
  /** Full qualified name of the optimistic locking column  */
  public static final ColumnName OPTIMISTIC_LOCKING_COLUMN = new ColumnName(TABLENAME, OPTIMISTIC_LOCKING_COLUMN_NAME);
</#if>
<#list columns as column>  
  /** Name of the column ${column.name} */
  private static final String COLUMN_NAME_${column.constant} = "${column.name}";
  /** Full qualified name of the column ${column.name} */
  public static final ColumnName COLUMN_${column.constant} = new ColumnName(TABLENAME, COLUMN_NAME_${column.constant});
</#list>
<#list associations as association>  
  /** Table name of association ${association.name} */
  public static final String ASSOCIATION_${association.constant}_TABLE_NAME = "${association.table}";
  /** Foreign key column ${association.foreignKey} of association table ${association.table} that references rows of this table */
  public static final ColumnName ASSOCIATION_${association.constant}_COLUMN_${association.foreignKeyConstant} = new ColumnName(ASSOCIATION_${association.constant}_TABLE_NAME, "${association.foreignKey}");
</#list>

  /**
   * Constructor
   * @param database the database persistency service
   */
  public Db${table.simpleEntityClass}(DatabasePersistencyService database)
  {
    super(database, 
      ${table.simpleEntityClass}.class,
      new Table(
        TABLENAME, 
        KeyType.${table.primaryKey.keyType},
        Arrays.asList( 
<#list columns as column>
  <#if column.isPrimaryKey()>
          new TableColumn(PRIMARY_KEY_COLUMN, Type.${table.primaryKey.sqlDataType}, Option.PRIMARY_KEY)<#if column_has_next>,</#if>
  <#elseif column.isParentKey()>
          new TableColumn(PARENT_FOREIGN_KEY_COLUMN, Type.${table.primaryKey.sqlDataType}, Option.PARENT_KEY)<#if column_has_next>,</#if>
  <#else> 
          new TableColumn(COLUMN_${column.constant}, Type.${column.sqlDataType}<#if column.isOptimisticLockingColumn()>, Option.USE_FOR_OPTIMISTICAL_LOCKING</#if><#if column.isLob()>, Option.LARGE_OBJECT</#if>)<#if column_has_next>,</#if>
  </#if>         
</#list>
<#if table.query??>
        ),
<#else>
        )
</#if>        
<#if table.query??>
        QUERY_TABLENAME,
        Arrays.asList( 
   <#list queryViewColumns as column>
          new ViewColumn(QueryView.VIEW_COLUMN_${column.constant}<#if column.alias??>, "${column.alias}"</#if>)<#if column_has_next>,</#if>
  </#list>
        )
</#if>
      )
    ); 
  }

  /**
   * @see DatabaseTableClassPersistencyService#createObjectFromResultSet(IPersistentTransaction, ResultSet)
   */
  @Override
  protected ${table.simpleEntityClass} createObjectFromResultSet(IPersistentTransaction transaction, ResultSet result) throws PersistencyException, SQLException
  {
<#assign row=1>
    return new ${table.simpleEntityClass}(
      database.get${table.primaryKey.method}(result, ${row}${table.primaryKey.additionalReadArgs})<#if (columnsWithoutPrimaryParentAndLob?size > 0 || table.parentKey??)>,</#if> // ${table.primaryKey.sql}
<#assign row=row+1>      
<#if table.parentKey??>
      database.get${table.parentKey.method}(result, ${row}${table.parentKey.additionalReadArgs})<#if (columnsWithoutPrimaryParentAndLob?size > 0)>,</#if> // ${table.parentKey.sql}
  <#assign row=row+1>      
</#if>            
<#list columnsWithoutPrimaryParentAndLob as column>
  <#if column.isPassword()>
    <#if column.optionalPasswordColumn??>
      database.optionalDecode(transaction, database.get${column.optionalPasswordColumn.method}(result, ${column.optionalPasswordColumn.resultSetRowNumber}${column.optionalPasswordColumn.additionalReadArgs}), database.get${column.method}(result, ${row}${column.additionalReadArgs}))<#if column_has_next>,</#if> // ${column.sql}
    <#else> 
      database.decode(transaction, database.get${column.method}(result, ${row}${column.additionalReadArgs}))<#if column_has_next>,</#if> // ${column.sql}
    </#if>
  <#else>
      database.get${column.method}(result, ${row}${column.additionalReadArgs})<#if column_has_next>,</#if> // ${column.sql}
  </#if>
  <#assign row=row+1>      
</#list>
    );
  }

  /**
   * @see DatabaseTableClassPersistencyService#writeDataToUpdateStatement(IPersistentTransaction, IPersistentObject, PreparedStatement)
   */
  @Override
  protected void writeDataToUpdateStatement(IPersistentTransaction transaction, ${table.simpleEntityClass} data, PreparedStatement stmt) throws PersistencyException
  {
<#assign row=1>
<#if table.parentKey??>      
    // ${table.parentKey.sql}
    database.set${table.parentKey.method}(stmt, ${row}, ${table.parentKey.additionalWriteArgs}, PARENT_FOREIGN_KEY_COLUMN);
  <#assign row=row+1>      
</#if>
<#list columnsWithoutPrimaryParentAndLob as column>
    // ${column.sql}
  <#if column.isOptimisticLockingColumn()>
    // optimistic locking value is already in the update query
  <#else>
    database.set${column.method}(stmt, ${row}, ${column.additionalWriteArgs}, COLUMN_${column.constant});
    <#assign row=row+1>
  </#if>
</#list>
    // ${table.primaryKey.sql}
    database.set${table.primaryKey.method}(stmt, ${row}, ${table.primaryKey.additionalWriteArgs}, PRIMARY_KEY_COLUMN);
  }

  /**
   * @see DatabaseTableClassPersistencyService#writeDataToInsertStatement(IPersistentTransaction, IPersistentObject, PreparedStatement)
   */
  @Override
  protected void writeDataToInsertStatement(IPersistentTransaction transaction, ${table.simpleEntityClass} data, PreparedStatement stmt) throws PersistencyException
  {
<#assign row=1>
    // ${table.primaryKey.sql}
    database.set${table.primaryKey.method}(stmt, ${row}, ${table.primaryKey.additionalWriteArgs}, PRIMARY_KEY_COLUMN);
<#assign row=row+1>
<#if table.parentKey??>      
    // ${table.parentKey.sql}
    database.set${table.parentKey.method}(stmt, ${row}, ${table.parentKey.additionalWriteArgs}, PARENT_FOREIGN_KEY_COLUMN);
  <#assign row=row+1>
</#if>
<#list columnsWithoutPrimaryAndParent as column>
    // ${column.sql}
    database.set${column.method}(stmt, ${row}, ${column.additionalWriteArgs}, COLUMN_${column.constant});
  <#assign row=row+1>
</#list>
  }

<#if table.fieldForOptimisticLocking??>
  @Override
  protected void writeDataToOptimisticUpdateStatement(IPersistentTransaction transaction, ${table.simpleEntityClass} data, PreparedStatement stmt)
  {
    database.set${table.fieldForOptimisticLocking.method}(stmt, ${numberOfColumns}, data.get${table.fieldForOptimisticLocking.name}(), COLUMN_${table.fieldForOptimisticLocking.constant});
  }
</#if>  
  
<#if table.query??>
  /**
   * This class defines constants for the columns that the ${table.query} view declares
   */
  public static class QueryView
  {
<#list queryViewColumns as column>
    /** Name of the column ${column.name} */
    private static final String VIEW_COLUMN_NAME_${column.constant} = "${column.name}";
    /** Full qualified name of the column ${column.name} */
    public static final ColumnName VIEW_COLUMN_${column.constant} = new ColumnName(QUERY_TABLENAME, VIEW_COLUMN_NAME_${column.constant});
</#list>  
  }
</#if>  
  
}
