package ${packageName};

import ch.ivyteam.db.sql.ColumnName;

/**
 * ----------------------------------------------------------------------<br>
 * This code was generated by the JavaClassPersistencyServiceImplemenationGenerator.<br>
 * Do not edit this class instead edit the meta information this class was generated of.<br>
 * ----------------------------------------------------------------------<br>
 * Class for view ${view.id}<br>
 * ----------------------------------------------------------------------<br>
 * This class is responsible to provide constants for the name and columns of the view ${view.id}
 * ----------------------------------------------------------------------<br>
 * ${view.comment}
 * ----------------------------------------------------------------------<br>
 */
public class ${className}
{
  /** Name of the DB View */
  public static final String VIEWNAME = "${view.id}";
<#list columns as column>  
  /** Name of the column ${column.name} */
  private static final String COLUMN_NAME_${column.constant} = "${column.name}";
  /** Full qualified name of the column ${column.name} */
  public static final ColumnName COLUMN_${column.constant} = new ColumnName(VIEWNAME, COLUMN_NAME_${column.constant});
</#list>
}
