
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 26 14:26:36 CEST 2023
//----------------------------------------------------

package ch.ivyteam.db.meta.parser.internal;

/** CUP generated interface containing symbol constants. */
@SuppressWarnings("all")
public interface Symbols {
  /* terminals */
  public static final int AS = 40;
  public static final int LEFT = 49;
  public static final int IDENTIFIER = 80;
  public static final int FROM = 42;
  public static final int TIME = 18;
  public static final int OUTER = 48;
  public static final int BIGINT = 10;
  public static final int TRIGGER = 33;
  public static final int RIGHT = 50;
  public static final int TABLE = 5;
  public static final int ILLEGAL = 82;
  public static final int ROW = 38;
  public static final int DATETIME_LITERAL = 79;
  public static final int BLOB = 13;
  public static final int COMMA = 74;
  public static final int JOIN = 46;
  public static final int CLOB = 14;
  public static final int INNER = 47;
  public static final int REFERENCES = 27;
  public static final int ALL = 45;
  public static final int INTEGER = 9;
  public static final int DATETIME = 16;
  public static final int INTEGER_LITERAL = 77;
  public static final int NOT = 69;
  public static final int VIEW = 6;
  public static final int AFTER = 34;
  public static final int FLOAT = 21;
  public static final int THEN = 63;
  public static final int STATEMENT = 39;
  public static final int NUMBER_LITERAL = 78;
  public static final int WHEN = 62;
  public static final int INTO = 7;
  public static final int SELECT = 41;
  public static final int NUMBER = 19;
  public static final int FULL = 51;
  public static final int R_PARENT = 72;
  public static final int INDEX = 26;
  public static final int UNION = 44;
  public static final int EQUAL = 54;
  public static final int USE = 67;
  public static final int DELETE = 29;
  public static final int DECIMAL = 20;
  public static final int EACH = 37;
  public static final int CHAR = 15;
  public static final int EXECUTE = 36;
  public static final int FOR = 66;
  public static final int GREATER = 58;
  public static final int L_PARENT = 71;
  public static final int ELSE = 64;
  public static final int DOT = 75;
  public static final int STRING_LITERAL = 76;
  public static final int BIT = 12;
  public static final int NULL = 68;
  public static final int SEMICOLON = 73;
  public static final int EOF = 0;
  public static final int COMMENT = 81;
  public static final int WHERE = 43;
  public static final int THIS = 32;
  public static final int DEFAULT = 70;
  public static final int IS = 60;
  public static final int UNIQUE = 25;
  public static final int DATE = 17;
  public static final int OR = 53;
  public static final int SET = 30;
  public static final int error = 1;
  public static final int NOT_EQUAL = 55;
  public static final int ON = 28;
  public static final int GREATER_EQUAL = 59;
  public static final int END = 65;
  public static final int VALUES = 8;
  public static final int LESS_EQUAL = 57;
  public static final int CREATE = 2;
  public static final int VARCHAR = 11;
  public static final int BEGIN = 35;
  public static final int CASE = 61;
  public static final int CASCADE = 31;
  public static final int UPDATE = 4;
  public static final int INSERT = 3;
  public static final int FOREIGN = 23;
  public static final int LESS = 56;
  public static final int PRIMARY = 22;
  public static final int AND = 52;
  public static final int KEY = 24;
}

